name: adomed_app
description: Application Adomed - Télémédecine
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  flutter_localizations:
    sdk: flutter

  # Packages UI/Design
  cupertino_icons: ^1.0.6
  lottie: ^3.1.2
  shimmer: ^3.0.0
  cached_network_image: ^3.3.1
  intl_phone_field: ^3.2.0
  table_calendar: ^3.1.2
  iconsax: ^0.0.8
  photo_view: ^0.15.0
  video_player: ^2.8.6
  shared_preferences: ^2.2.2
  dots_indicator: ^3.0.0

  # Firebase
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.5
  firebase_messaging: ^14.9.4
  firebase_storage: ^11.7.7
  firebase_app_check: ^0.2.2+1

  # Utilitaires
  flutter_dotenv: ^5.1.0
  flutter_local_notifications: ^17.2.1
  flutter_tts: ^4.0.2
  geocoding: ^3.0.0
  geolocator: ^12.0.0
  google_generative_ai: ^0.4.6
  http: ^1.2.1
  image_picker: ^1.1.2
  intl: ^0.20.0
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  flutter_sound: ^9.3.0
  share_plus: ^9.0.0
  url_launcher: ^6.3.0
  uuid: ^4.4.2
  video_thumbnail: ^0.5.3
  
  # State Management & Gauges
  provider: ^6.1.2
  syncfusion_flutter_gauges: ^30.2.5

  # Spécifiques
  country_state_city_picker: ^1.2.8
  device_info_plus: ^10.1.0
  file_picker: ^8.0.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_native_splash: ^2.4.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/services/
    - assets/images/marketplace/
    - assets/images/offers/ 
    - .env
    - assets/fonts/
    - assets/lottie/

  fonts:
    - family: Mulish
      fonts:
        - asset: assets/fonts/Mulish-VariableFont_wght.ttf
        - asset: assets/fonts/Mulish-Italic-VariableFont_wght.ttf
          style: italic