name: adomed_app
description: Application Adomed - Télémédecine
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Packages UI/Design
  cupertino_icons: ^1.0.6
  lottie: ^3.1.0
  shimmer: ^3.0.0
  cached_network_image: ^3.3.1
  intl_phone_field: ^3.2.0
  table_calendar: ^3.1.0
  iconsax: ^0.0.8
  photo_view: ^0.15.0
  video_player: ^2.8.2
  shared_preferences: ^2.2.2
  dots_indicator: ^3.0.0

  # Firebase (Versions compatibles avec un ancien Xcode)
  firebase_core: ^2.17.0
  firebase_auth: ^4.10.1
  cloud_firestore: ^4.9.3
  firebase_messaging: ^14.7.0
  firebase_storage: ^11.2.8
  firebase_app_check: ^0.2.1+8

  # Utilitaires
  flutter_dotenv: ^5.1.0
  flutter_local_notifications: ^16.3.2
  flutter_tts: ^3.8.3
  geocoding: ^2.1.1
  geolocator: ^10.1.0
  google_generative_ai: ^0.2.2
  http: ^1.1.0
  image_picker: ^1.0.4
  intl: ^0.18.1
  path_provider: ^2.1.1
  permission_handler: ^11.1.0
  flutter_sound: ^9.2.13
  share_plus: ^7.2.1
  url_launcher: ^6.2.1
  uuid: ^4.2.1
  video_thumbnail: ^0.5.3
  
  # State Management & Gauges
  provider: ^6.1.1
  syncfusion_flutter_gauges: ^23.2.7

  # Spécifiques
  country_state_city_picker: ^1.2.8
  device_info_plus: ^9.1.1
  file_picker: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_native_splash: ^2.4.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/services/
    - assets/images/marketplace/
    - assets/images/offers/ 
    - .env
    - assets/fonts/
    - assets/lottie/

  fonts:
    - family: Mulish
      fonts:
        - asset: assets/fonts/Mulish-VariableFont_wght.ttf
        - asset: assets/fonts/Mulish-Italic-VariableFont_wght.ttf
          style: italic