name: Build iOS IPA
on: workflow_dispatch
jobs:
  build_ios:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      
      # 1. Configurer Java (Requis pour certaines versions de Flutter)
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      # 2. Installer Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          
      - name: Install dependencies
        run: flutter pub get

      # 3. Installer Certificats Apple
      - name: Install Apple Certificate and Profile
        env:
          BUILD_CERTIFICATE_BASE64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
          P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
          BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.BUILD_PROVISION_PROFILE_BASE64 }}
          KEYCHAIN_PASSWORD: "temporary_password"
        run: |
          # Définir les chemins
          CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
          PP_PATH=$RUNNER_TEMP/build_pp.mobileprovision
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db

          # Décoder les secrets
          echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode -o $CERTIFICATE_PATH
          echo -n "$BUILD_PROVISION_PROFILE_BASE64" | base64 --decode -o $PP_PATH

          # Créer et déverrouiller le trousseau
          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH

          # Importer le certificat
          security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security list-keychain -d user -s $KEYCHAIN_PATH

          # Installer le profil de provisionning
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles/

      # 4. Construire l'IPA (Avec forcage Manuel)
      - name: Build IPA
        run: |
          flutter build ipa --release --export-options-plist=ios/ExportOptions.plist -- --build-args CODE_SIGN_STYLE=Manual PROVISIONING_PROFILE_SPECIFIER="Adomed App Store Distribution" DEVELOPMENT_TEAM="P534537N35" CODE_SIGN_IDENTITY="Apple Distribution"

      # 5. Sauvegarder l'IPA pour le téléchargement
      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: Adomed-IPA
          path: build/ios/ipa/*.ipa
